### ISSUE TITLE
Update with latest JMdict?

### ISSUE THREAD

**Issue by fasiha** [scriptin/jmdict-simplified#13]
Forgive me for bugging you, I wondered if you could publish an update with the latest JMdict? Version 3.0.1 was released 1.5 years ago and today I came across a [word](http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=2068329) that had been added earlier this year and wasn't in jmdict-simplified. Thank you!!

**Comment by scriptin** [comment]
Hello again, @fasiha

I've just made [a new workflow](https://github.com/scriptin/jmdict-simplified/blob/master/.github/workflows/update-dist.yml) for making updates and created [a new release](https://github.com/scriptin/jmdict-simplified/releases/tag/3.0.1+20200725163554). Now, if you need an update, it's just pressing 2 buttons for me, so don't hesitate to ask.

I haven't checked the resulting files in detail, but everything seems to be okay after a quick look. Please let me know if something is broken.

**Comment by fasiha** [comment]
As always, works perfectly, thank you so much for your continued support and hard work!
