### ISSUE TITLE
Automatically update when source dictionaries are updated

### ISSUE THREAD

**Issue by scriptin** [scriptin/jmdict-simplified#14]
Create a new workflow that periodically (how often?):

1. Downloads the source files
2. Checks if they were updated by comparing file hashes. Hashes from the last build need to be stored in the repository to be able to compare
3. If any change was detected, trigger an existing update action to create a new release
4. If possible, set a release notes message about which dictionary was updated and triggered a build

Limitations: [free 2000 minutes per month](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions)

**Comment by fasiha** [comment]
Very cool!, I didn’t know about Github Actions!

I’d be very happy with an update once a month (since minutes reset every month).

I am not sure if JMdict updates more often or less often than JMnedict—the latter takes much longer to run. Also maybe you could run JMdict more often than JMnedict.

It looks like the cost is 8$/1000 minutes per month if you exceed the free 2000 minutes threshold—assuming the boxes Github gives you can finish a full build in an hour every month, I’m happy to cover the cost for a year.

**Comment by scriptin** [comment]
Thanks for your input, @fasiha 

With just one update per month 2000 minutes is way more than enough. The full build (all dictionaries, all versions) is less than 10 minutes. Checking if something was updated will take less than 2 minutes.

I'll go with once a month updates.

> Also maybe you could run JMdict more often than JMnedict.

I was thinking of splitting this repo into 2 separate once eventually, but right now it will be fine to rebuild everything, just for the convenience of usage.

**Comment by scriptin** [comment]
I updated the workflow. Manual testing works fine. It will run on the 1st and 15th every month. Once it will update at least once, I'll close this issue.

**Comment by fasiha** [comment]
@scriptin hope you've been well! Is there anything I can do to help troubleshoot what happened to the automated releases? The last release was on October 2020 and I'm guessing the [release config](https://github.com/scriptin/jmdict-simplified/blob/master/.github/workflows/release.yml) needs some editing but I'm not sure where to find logs to find what's causing the build to fail.

**Comment by fasiha** [comment]
Ooh, trying a local build and perhaps it's related to this:
```xml
<!-- Rev 1.09
        Added the g_type attribute
-->
```
because I see this error:
```
Execution failed for task ':jmdictCommonConvert'.
> org.basex.query.QueryException: Unknown gloss type 'tm' on entity 1074950
```
