### ISSUE TITLE
JMdict version number?

### ISSUE THREAD

**Issue by fasiha** [scriptin/jmdict-simplified#2]
It would be useful if the JSON file included another key that contained the JMdict version number or release date or some way to identify which copy of JMdict it corresponded to.

In my copy of `JMdict_e` XML database, I see a comment:
```xml
<!-- JMdict created: 2016-12-28 -->
```
I realize it might be hard to extract that, via XQuery, and insert it into the JSON, but perhaps this could be done outside XQuery, as a post-processing step?

I ask about this because we have found that entries come and go as JMdict matures, and it’s conceivable that a cross-reference made today might be invalid tomorrow. If cross-references included, as metadata, the JMdict version, that’s a step at resolving such problems when they inevitably arise.

**Comment by scriptin** [comment]
Thank you, @fasiha 

I added separate fields for date and revisions mentioned in the comments on top of the original XML file.
