### ISSUE TITLE
"misc" tags for senses

### ISSUE THREAD

**Issue by aehlke** [scriptin/jmdict-simplified#22]
I would appreciate having the "misc" tags for senses, particularly so that I can filter / label language that is less relevant or sensitive such as "chn" (children's language) and historical terms. Thank you

**Comment by scriptin** [comment]
@aehlke Good catch! Thank you for noticing this. I missed this field when created a new converter.

You can grab the fixed version in the latest release: <https://github.com/scriptin/jmdict-simplified/releases/tag/3.2.1%2B20230103160328>

**Comment by aehlke** [comment]
Thank you so much!
