### ISSUE TITLE
KanjiDic?

### ISSUE THREAD

**Issue by aehlke** [scriptin/jmdict-simplified#26]
Are you interested in adding kanjidic, or have thoughts on what already covers that well for JSON?

**Comment by scriptin** [comment]
I will to take a look, as I'm not familiar with it.

**Comment by aehlke** [comment]
Here is an older repo for inspo: https://github.com/matteobruni/kanji-data

**Comment by aehlke** [comment]
And stroke data: https://www.edrdg.org/krad/kradinf.html

**Comment by scriptin** [comment]
Done. See the latest release. Let me know if you have any questions or problems.

For radicals, I have opened a separate issue, will review it soon.

**Comment by aehlke** [comment]
Thank you so much!!! <3
