### ISSUE TITLE
Kanjidic 3.5.0 json is missing some radicals

### ISSUE THREAD

**Issue by skibitsky** [scriptin/jmdict-simplified#30]
The `radicals` array in Kanjidic json has only one element of each type (`classical` or `nelson_c`) in every kanji.

For example, kanji 家 has only one `classical` radical element with value 40 (宀). Another radical with value 152 (豕) is missing from the array.

**Comment by scriptin** [comment]
Hello, and thank you for reporting the issue.

Sorry I haven't been able to investigate this. Too busy dealing with life. 😩 I will look into it eventually, but can't tell when exactly.

**Comment by scriptin** [comment]
Hello @skibitsky 

I've finally got around to checking this error, and here's what I see in the original XML file for the kanji you've mentioned:

```xml
<!-- Entry for Kanji: 家 -->                                                               
<character>                                                                                
<literal>家</literal>                                                                      
<codepoint>                                                                                
<cp_value cp_type="ucs">5bb6</cp_value>                                                    
<cp_value cp_type="jis208">1-18-40</cp_value>                                              
</codepoint>                                                                               
<radical>                                                                                  
<rad_value rad_type="classical">40</rad_value>                                             
</radical> 
<!-- Omitted -->
</character>
```

Here's what the documentation says about this field:

> * the radical.
>   * classical - as recorded in the KangXi Zidian.

So, it's not a full decomposition of this character, but rather just the radical, as listed in KangXi Zidian. All the sources I've checked ([jisho](https://jisho.org/search/%E5%AE%B6%20%23kanji), [wiktionary](https://en.wiktionary.org/wiki/%E5%AE%B6)) list the radical 40 (宀) as the only radical for this character (but they also list the other component as well, but it's not a radical), so the original XML file is listing exactly that, and my scripts preserve this data.

So, I believe there is no issue here. It's exactly as specified by the authors, and there is no conversion error either.

If you're looking for the full decomposition, I suggest that you look into **kradfile** instead. Here's this character from `kradfile-3.5.0.json`:

```
"家": ["宀","豕"],
```

**Comment by scriptin** [comment]
As a note, the difference between radicals and components is the following:

- Components are constituent elements of kanji, which are either kanji themselves, or at least they are patterns repeating across multiple kanji.
- Radicals are components (but not all components are radicals!) used for look-up tables, like dictionary indices.

Which component is used as a radical is a bit arbitrary. The authors of indices/lists decide that based on their knowledge, traditions, etc. See [Chinese character radicals](https://en.wikipedia.org/wiki/Chinese_character_radicals) for details.
