### ISSUE TITLE
low quality words and translations

### ISSUE THREAD

**Issue by sgehrman** [scriptin/jmdict-simplified#32]
I made a flash card app using your jmdict-eng-common-3.6.1.json file.

I showed it to my Japanese wide and every single word I showed her she said the word was wrong, or old fashion, or obscure and useless.

Do you have better data?  This data is totally useless.

**Comment by sgehrman** [comment]
for example.  Look at 'store name'  it gives Tenmei.  Tenmei means "Tenmei is a Japanese era name for the years between the An'ei Era and before the Kansei Era, from April 1781 through January 1789. The reigning emperor was Kōkaku Tennō"

from google translate.  My wife said there is a store called Tenmei.  

Why would anyone learning Japanese need to know the name of a retail store.  Pathetic quality.

**Comment by scriptin** [comment]
Hello @sgehrman 

I'm not the author of the data. This project is only converting the original JMdict to a different format, with various minor *technical* improvements. I do not add, edit, or remove any data from the original. If you have any questions regarding the content of this dictionary, you should ask the original authors. You can find all the links in [the readme](https://github.com/scriptin/jmdict-simplified/blob/master/README.md) for this project.

As for the facts that some words in the dictionary are archaic, such entires are marked with special tags, such as `"arch"`. You can find the list of tags in the beginning of each file, and use it to filter the data to fit your needs. All the necessary information to get you started can be found in the readme I've linked above.
