### ISSUE TITLE
Cloning takes forever, remove xml files ?

### ISSUE THREAD

**Issue by gotenxds** [scriptin/jmdict-simplified#4]
The xml files makes the project wighe over 80M, clone takes a long time for no good reason.
If someone needs to run the code he can just download the latest xml file from the site.

**Comment by scriptin** [comment]
Sorry, I only removed resulting JSON files and forgot to actually delete the original JMDict file. I'll add an automatic downloading script for the original file because I don't want any manual steps in the build.
