### ISSUE TITLE
A huge, huge onegai: JMnedict?

### ISSUE THREAD

**Issue by fasiha** [scriptin/jmdict-simplified#6]
I'm so hesitant and ashamed to ask this—have you ever thought of a `jmnedict-simplified`, i.e., a JSON version of [JMnedict, the Japanese names dictionary](http://www.edrdg.org/enamdict/enamdict_doc.html)? A glance at the the XML file's DTD shows a lot of parallels with JMdict, but I'm not familiar enough with XPath to surmise how much or how little work this would be, so I'll just say that I love working with jmdict-simplified and would love a similar resource for JMnedict. Thanks for listening 🙇‍♂️!

**Comment by scriptin** [comment]
It seems similar enough in general layout, with some differences in entries inner structure. I think it would be pretty easy to extend/generalize the current code to incorporate this dictionary. I will look into that in the next weekend.

Thank you for the suggestion.

**Comment by scriptin** [comment]
OK, everything seems to be working. Updated the docs, pushed the release.

**Comment by fasiha** [comment]
😲 thank you 😁 you are so fantastic!!!

**Comment by vnenkpet** [comment]
I just check in today to see if anything's new and this is a great surprise :+1:

**Comment by fasiha** [comment]
@vnenkpet I “watch” this repository, so GitHub notifies me whenever @scriptin adds more magic 🧙‍♂️!

**Comment by DJTB** [comment]
There's a few of us creepy watchers ;)
